name: Testing
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 14.2
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
